version: '3'
services:
  mongodb:
    image: mongo
    container_name: url-shortener-mongodb
    ports:
      - "27016:27017"
    networks:
      - proxynet
    volumes:
      - "mongodb_data:/data/db"
  redis:
    image: redis
    container_name: url-shortener-redis
    ports:
      - "6378:6379"
    networks:
      - proxynet
    volumes:
      - "redis_data:/data/cache"
  url-shortener:
    build: .
    container_name: url-shortener-service
    ports:
      - "8081:8081"
    networks:
      - proxynet
    depends_on:
      - mongodb
      - redis

networks:
  proxynet:
    external:
      name: proxynet

volumes:
  mongodb_data:
  redis_data:
