version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - "mongodb_data:/data/db"
  url-shortener:
    build: .
    container_name: url_shortener
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  mongodb_data: