version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27016:27017"
    volumes:
      - "mongodb_data:/data/db"
  redis:
    image: redis
    container_name: redis_db
    ports:
      - "6378:6379"
    volumes:
      - "redis_data:/data/cache"
  url-shortener:
    build: .
    container_name: url_shortener
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
volumes:
  mongodb_data:
  redis_data:
