name: Test my app

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build image
            run: task build

          - name: Run tests
            run: |
              task test