name: Test my app

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Up server
            run: |
              docker-compose up --build -d

          - name: Run tests
            run: go test ./tests