name: Test my app

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Up server
              run: |
                docker-compose up --build -d
                sleep 60

            - name: Run tests
              run: go test ./tests